SCXA SolrCloud image
ebi-gene-expression-group/atlas-containers pull request #5
Opened 2021-05-19 14:25 UTC by alfonsomunozpomer

An image that contains an empty SolrCloud instance ready to use in testing and CI workflows. It’s just one SolrCloud node running with an embedded ZooKeeper.

I’ve added an action to publish to Quay but until it runs I won’t know for sure it works.

2021-05-19 14:42 UTC, pinin4fjords requested changes

2021-05-19 14:42 UTC, pinin4fjords commented on .github/workflows/scxa-solrcloud.yaml
> +    - name: Read internal update version
You don't have the RUNNER_VERSION issue the other container has, so you should remove this step...

2021-05-19 14:42 UTC, pinin4fjords commented on .github/workflows/scxa-solrcloud.yaml
> +        tags: latest ${{ steps.gettag.outputs.tag }}${{ steps.getversion.outputs.version }}
.. and remove the getversion reference here.

```suggestion
        tags: latest ${{ steps.gettag.outputs.tag }}
```

2021-05-19 16:32 UTC, alfonsomunozpomer commented
Thanks @pinin4fjords for the suggestions. I just copied the GH Actions Runner YAML just in case there were some particularities of GH actions I wasn’t aware of. I modified the action as per your suggestions. Let me know how that looks now.

2021-05-19 18:16 UTC, pinin4fjords approved these changes

2021-05-19 18:16 UTC, pinin4fjords commented
Looks good!

2021-05-19 18:23 UTC, pinin4fjords commented
Though @alfonsomunozpomer actually, we might want chat with @pcm32 about the submodule pattern. It might be better to use the git checkout action instead to clone the additional repos https://github.com/actions/checkout#checkout-multiple-repos-nested

2021-05-21 10:26 UTC, merged

2021-05-21 10:37 UTC, alfonsomunozpomer commented
Ah, the image build failed because of submodules not being in the expected path. I’ve created and assigned https://github.com/ebi-gene-expression-group/atlas-containers/issues/6.